version: '3.8'

services:
  api:
    build: ./backend
    container_name: polling-api
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=polling
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    container_name: polling-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run start

  db:
    image: postgres:14
    container_name: polling-db
    restart: always
    environment:
      POSTGRES_DB: polling
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: polling-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
